### PR TITLE
stop polling when queue is full

### PR DESCRIPTION
**Pull request by dophinlife**

### CODE REVIEW

**Comment by chainone** [comment]
logger.warn("All workers are busy, not polling.  queue size {}, max {}"
是不是改成：
“Worker queue is full, stop polling.  Queue size: {},  max: {}”

**Comment by chainone** [comment]
new LinkedBlockingQueue<Runnable>(workerQueueSize);

we'd better to create this queue in the init block

**Comment by chainone** [comment]
get the remaining capacity of worker queue to prevent queue full exception

**Comment by chainone** [comment]
int | remainingCapacity()Returns the number of additional elements that this queue can ideally (in the absence of memory or resource constraints) accept without blocking.
-- | --

**Comment by chainone** [comment]
It seems we can not directly get capacity out of the queue, so that we may have to keep the queueSize member variable as queueSize would be printed in log

**Comment by chainone** [comment]
// this doc comment is a modified copy of the inherited doc comment,
    // without the reference to unlimited queues.
    /**
     * Returns the number of additional elements that this queue can ideally
     * (in the absence of memory or resource constraints) accept without
     * blocking. This is always equal to the initial capacity of this queue
     * less the current {@code size} of this queue.
     *
     * <p>Note that you <em>cannot</em> always tell if an attempt to insert
     * an element will succeed by inspecting {@code remainingCapacity}
     * because it may be the case that another thread is about to
     * insert or remove an element.
     */
    public int remainingCapacity() {
        return capacity - count.get();
    }

**Comment by dophinlife** [comment]
Without any initialization in init block, so I don't think it's better to create queue in this block .

**Comment by chainone** [comment]
new LinkedBlockingQueue(workerQueueSize);

we'd better to create this queue in the init block

**Pull request merged**
